### ISSUE TITLE
小白请教怎么制作数据集和训练模型

### ISSUE THREAD

**Issue by kyerbas** [Tang1705/Baidu-Rot-Validate#1]
小白请教怎么制作数据集和训练模型

**Comment by Tang1705** [comment]
**Python-based**

**数据集：**图片的获取可以通过代码循环多次访问同一网站进入安全验证页面，然后通过解析 html 获取图片链接进行保存，如果有其他方法可以更方便进入安全验证页面最好，例如有人建议过 https://ziyuan.baidu.com/linksubmit/url/ 这个网页，但我没有尝试过，图片的加载可能需要一段时间，所以可以延迟几秒再解析网页获得图片或通过异步、判断网页加载完毕等方式。下载大概1500张左右的图片，然后人工筛选（减少训练时间）出不重复的图片。通过第三方库（包）对图片进行旋转，生成360个角度的图片（建议以1、2、3……这样的序列给图片命名）。为了给图片打标签，可以写一个循环，读入不同的图片（不同角度的同一张图片建议放在一个文件夹下），手工确认一张图片的正向，输入程序中，通过图片名与正向图片名称的差给图片打角度标签，从而完成数据集的建立。

**训练模型：**模型的训练可以自行选择，例如 PyTorch、Keras 等自带的网络模型，均可尝试，选择一个效果最好的模型，只需将最终的预测类别修改为你的分类类别即可，例如我提到的直接预测的拖动条的距离，或者你想训练角度，均可。
