### ISSUE TITLE
哈喽，感谢分享，我这边也有一个旋转验证码识别的需求，想问一下可以开源一下数据和数据集制作脚本吗，谢谢？

### ISSUE THREAD

**Issue by zhang-ling-yun** [Tang1705/Baidu-Rot-Validate#2]

**Comment by Tang1705** [comment]
感谢留言。

数据集方面我个人认为涉及到一些敏感性，不方便开源，方便的话我们可以私下交流。

脚本方面由于时间问题已经丢失，而且实现也不难，可以参考 readme 的讲解自己实现，后续如果问的人多的话我可能会找个时间复现一下，希望理解。

**Comment by Tang1705** [comment]
> No description provided.

https://github.com/Tang1705/Baidu-Rot-Validate/issues/1
