### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by createalltheworld** [Tang1705/Baidu-Rot-Validate#3]
你好，大佬，你这个代码是没有训练集保存了训练模型是吗，如果想再训练的话是不是需要自己去抓取验证码图片啊

**Comment by Tang1705** [comment]
原来是有数据保存的，但是我认为涉及到数据隐私和敏感就没有放上来，前段时间电脑出故障，现在应该是没有了

**Comment by createalltheworld** [comment]
那你这保存的模型可以直接用吗发自我的华为手机-------- 原始邮件 --------发件人： Tang ***@***.***>日期： 2022年10月31日周一 12:58收件人： Tang1705/Baidu-Rot-Validate ***@***.***>抄送： createalltheworld ***@***.***>, Author ***@***.***>主    题： Re: [Tang1705/Baidu-Rot-Validate] 数据集 (Issue #3)

原来是有数据保存的，但是我认为涉及到数据隐私和敏感就没有放上来，前段时间电脑出故障，现在应该是没有了

**Comment by Tang1705** [comment]
可以
