### ISSUE TITLE
有现成的api吗？高中研究性学习赶进度没时间成本研究

### ISSUE THREAD

**Issue by Edmounds** [Tang1705/Baidu-Rot-Validate#4]
readmd里没有告知如何操作。本人被百度这个验证搞崩溃了，我换个代理，用playwright开一个全新的浏览器还是一样会出来这个页面，不知道原理是什么，现在人很懵。。。

**Comment by Tang1705** [comment]
> readmd里没有告知如何操作。本人被百度这个验证搞崩溃了，我换个代理，用playwright开一个全新的浏览器还是一样会出来这个页面，不知道原理是什么，现在人很懵。。。

python 开发可以参考 https://github.com/ShortCJL/RotateCode
java 开发可先将训练获得的模型进行转化

`python
import torch
import torchvision
import torch.nn as nn

model = # instance of your model
model.load_state_dict(torch.load("your model.pth")["model_state_dict"])

# Switch the model to eval model
model.eval()

# An example input you would normally provide to your model's forward() method.
example = torch.rand(1, 3, 128, 128)

# Use torch.jit.trace to generate a torch.jit.ScriptModule via tracing.
traced_script_module = torch.jit.trace(model, example)

# Save the TorchScript model
traced_script_module.save("your model.pt")
`

**Comment by Tang1705** [comment]
> readmd里没有告知如何操作。本人被百度这个验证搞崩溃了，我换个代理，用playwright开一个全新的浏览器还是一样会出来这个页面，不知道原理是什么，现在人很懵。。。

python 开发可以参考 https://github.com/ShortCJL/RotateCode
java 开发可先将训练获得的模型进行转化
之后，便可通过 DJL 加载模型并作出预测，并借助其他工具来操作浏览器实现验证（为不限制大家思路，在此不放出我的实现代码）。

**Comment by Edmounds** [comment]
兄弟你爬过百度贴吧吗？大量的那种？我现在没思路了

**Comment by Tang1705** [comment]
没有，但是我爬过百度搜索，应该一样，只要能绕过一次基本就不会再遇到百度验证了

**Comment by Edmounds** [comment]
> 

我试过了，手动绕过之后，再爬段时间又会出来的。我现在遇到一个更麻烦的问题就是贴吧的回复使用js渲染的，我用scrapy-playwright爬没什么经验，而且不仅国内研究这个的人很少，而且爬取速度很慢，就像问一下有没有其它方法能get到回复的数据。

**Comment by Edmounds** [comment]
我现在基本想放弃了，这个研究性学习太消耗我的精力了，直接用百度指数算了，就不用爬虫获取贴吧的评论数据了。

**Comment by Tang1705** [comment]
> 我试过了，手动绕过之后，再爬段时间又会出来的。我现在遇到一个更麻烦的问题就是贴吧的回复使用js渲染的，我用scrapy-playwright爬没什么经验，而且不仅国内研究这个的人很少，而且爬取速度很慢，就像问一下有没有其它方法能get到回复的数据。

我也不是研究这个的，确实这种情况下只能选择其他方式了

**Comment by lumina37** [comment]
> 我现在基本想放弃了，这个研究性学习太消耗我的精力了，直接用百度指数算了，就不用爬虫获取贴吧的评论数据了。

现成的https://github.com/Starry-OvO/aiotieba ，我怕脚本战神到处宣传就改了个英文简介

**Comment by Edmounds** [comment]
> > 我现在基本想放弃了，这个研究性学习太消耗我的精力了，直接用百度指数算了，就不用爬虫获取贴吧的评论数据了。
> 
> 现成的https://github.com/Starry-OvO/aiotieba ，我怕脚本战神到处宣传就改了个英文简介

好的谢谢！
